- README.md
- lang/en.json
- lang/ru.json
- lang/sk.json
- lang/ua.json
> Try to fix English translation, add Russian, Ukrainian, and 🇸🇰 SLOVAK 🇸🇰 variants

- config/auth.example.json
- config/config.example.json
- lang/en.json
- lang/ru.json
- lang/sk.json
- lang/ua.json
Now all language and config files have a link to a proper schema.json file.
Closes #8.
> Added reference to schema files

- lib/commands/basic/HelpCommand.js
> Fix command not resolving on calling HelpCommand

- .editorconfig
- lib/classes/CommandsRegistry.js
- lib/classes/Config.js
- lib/classes/Lang.js
- lib/classes/MessageParser.js
Minor JSDoc improvements for several classes.
Also contains editorconfig changes about comments wrapping and maximal line size.
Note: Konstantin is actually me, but on the different machine. I forgot that I have different default git configuration for pushing.
> Minor JSDoc improvements

- .eslintrc.json
- package-lock.json
- package.json
> ESLint configured

- lang/en.json
- lib/classes/Bot.js
- lib/classes/Lang.js
- lib/classes/Utils.js
- lib/commands/basic/PingCommand.js
Implementation for ping command. Also, merged function for generating time string from previous bot version.
Current bot uptime can be requested from static `Bot.getUptimeString()` method.
Closes #13.
> Ping command implementation

- .editorconfig
- config/.gitignore
- config/auth.example.json
- config/db.example.json
- lib/classes/Database.js
- lib/database/models/BaseModel.js
- lib/schemas/db.schema.json
- package-lock.json
- package.json
Separate file for database settings. Also has a proper schema.json
Added in-memory sqlite database as dev-dependency for debug purposes. Can be set in db.json
Added ability to set settings for connection pool. Optional.
Closes #15
Closes #21
> Temporary database configuration

- lib/classes/CommandsRegistry.js
- lib/commands/BaseCommand.js
- lib/commands/basic/PingCommand.js
Now on bot initialization every command will be checked for availability of required properties such as static `code` and static `category`. This two properties required for calling this commands and showing it on HelpCommand.
> Checking for correct commands settings on initialization

- lib/classes/CommandContext.js
- lib/classes/MessageParser.js
- lib/classes/embed/DefaultEmbed.js
- lib/classes/embed/ErrorEmbed.js
- lib/commands/BaseCommand.js
- lib/commands/basic/AboutCommand.js
- lib/commands/basic/HelpCommand.js
- lib/commands/basic/PingCommand.js
Closes #28 — Implementing class.
> Command context class

- init/db-init.js
- init/devdb-init.js
- package-lock.json
- package.json
NPM script to easily initialize database for development purposes and accept migrations on it.
> Init scripts. Dev database

- lang/en.json
- lib/classes/Utils.js
- lib/commands/BaseCommand.js
- lib/commands/basic/HelpCommand.js
- lib/commands/guild/PrefixCommand.js
Here implementation of detailed information showing in `HelpCommand`. Also contains some changes for `BaseCommand` `getExamples` static method.
> HelpCommand: Detailed command information handling

- lib/classes/Bot.js
- lib/classes/Database.js
- lib/classes/MessageParser.js
- lib/classes/VoiceStateManager.js
- lib/classes/base/BaseTask.js
- lib/classes/tasks/TasksQueue.js
- lib/commands/guild/LogSettingsCommand.js
- lib/commands/guild/PrefixCommand.js
- lib/database/migrations/20201107144345-set-voice-table-primary-key-autoincrement.js
- lib/database/models/DocumentModel.js
- lib/database/models/GuildChannelModel.js
- lib/database/models/GuildMemberModel.js
- lib/database/models/GuildModel.js
- lib/database/models/MessageStatisticsModel.js
- lib/database/models/TaskModel.js
- lib/database/models/UserModel.js
- lib/database/models/VoiceStatistics.js
- lib/database/models/VoiceStatisticsModel.js
- lib/types/types.d.ts
All model was renamed from `<Name>` to `<Name>Model` to prevent JSDoc types from collision with DiscordJS classes.
> Voice stats and model names refactoring

- lang/en.json
Fixed a little typo in permissions localization
> EN localization fix

- lang/en.json
- lib/classes/LogsProcessor.js
- lib/classes/MessageProcessor.js
- lib/classes/commands/MessageParser.js
- lib/classes/localization/Lang.js
- lib/classes/tasks/commands/ReminderTask.js
- lib/classes/validation/Validators.js
- lib/commands/basic/AboutCommand.js
- lib/commands/basic/LanguageCommand.js
- lib/commands/guild/LanguageCommand.js
- lib/commands/guild/LogSettingsCommand.js
+ Added guild prefix mention in `about` command.
+ Added calling `about` command on bot mention without any other text.
+ Changed about command category from `basic` to `guild`.
+ Changed error on changing bot language to non-existing one.
+ Fixed #56 logging command localization missing.
+ Fixed #55 enabling and disabling all events at once.
+ Fixed arguments length validation for command context.
+ Fixed promise rejection happening on `ReminderTask` when user closed access to his DM.
+ Fixed promise rejection on `LogsProcessor.#resolveMemberRemove`
> [WIP] About command changes and other bugfixes

- lang/en.json
- lib/classes/LogsProcessor.js
- lib/classes/Utils.js
- lib/classes/statistics/VoiceStateManager.js
- lib/schemas/language.schema.json
+ Added private logs (message attachments, message updates, message deletion)
+ Fix #60 events duplication
> Private logs

- index.js
- lang/en.json
- lib/categories/HiddenCategory.js
- lib/classes/CognitumClient.js
- lib/classes/CognitumShardingManager.js
- lib/classes/ConfigManager.js
- lib/classes/Database.js
- lib/classes/Utils.js
- lib/classes/base/BaseModel.js
- lib/classes/commands/CommandsRegistry.js
- lib/classes/errors/commands/DocumentError.js
- lib/classes/localization/Lang.js
- lib/classes/statistics/VoiceStateManager.js
- lib/classes/tasks/TaskLoader.js
- lib/classes/tasks/TasksQueue.js
- lib/classes/tasks/internal/MonitoringStatsTask.js
- lib/commands/utils/DocumentCommand.js
- package-lock.json
- package.json
- shard.js
+ Added documents management command with (closes #43 from older version of bot);
+ Added hidden category for not fully implemented commands;
+ Changed custom log command with winston logger library;
+ Fix #63 TaskQueue incorrect time fetching causing late reminder call.
> Documents commands and some bugfixes

- lang/en.json
- lang/ru.json
> Added detailed error message to the russian localization (#89)

- lib/classes/LogsProcessor.js
Problem was caused by DiscordJS breaking change on sending messages to the channel.
> Fix logging embed messages are not sent correctly

- .github/workflows/codeql-analysis.yml
- lang/en.json
- lib/classes/errors/commands/InvalidLoggingChannelError.js
- lib/commands/guild/LogSettingsCommand.js
- lib/schemas/language.schema.json
- package-lock.json
- package.json
+ Added more detailed errors when selecting invalid channels as private/public logging channels. (Closes #88)
> Added more detailed information about invalid channels when setting up public or pirvate logging output channels

- lib/commands/stats/TopCommand.js
- package-lock.json
> Changes to the behavior of `top` command

- lib/commands/stats/TopCommand.js
- lib/commands/utils/DocumentCommand.js
> Increased page size of several commands from 10 to 20

- lib/classes/LogsProcessor.js
> Fixed crash caused by `LogsProcessor` on message deletion

- lib/database/migrations/20230201191610-create-indexes-for-highload-tables.js
- Trying to resolve #154 by adding indexes to those tables.
> Added database indexes for the messages and voice tables
